// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VRBrowserCommonGRPCProtos/BrowserInterop/ConnectEmissary.proto
// </auto-generated>
// Original file comments:
// Common Ping Service (prototype) 
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace VRWorlds.Schemas.Browser.InterOp {
  public static partial class ConnectEmissary
  {
    static readonly string __ServiceName = "VRWorlds.Schemas.Browser.InterOp.ConnectEmissary";

    static readonly grpc::Marshaller<global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest> __Marshaller_VRWorlds_Schemas_Browser_InterOp_ConnectEmissaryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn> __Marshaller_VRWorlds_Schemas_Browser_InterOp_ConnectEmissaryReturn = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn.Parser.ParseFrom);

    static readonly grpc::Method<global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest, global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn> __Method_ConnectEmissary = new grpc::Method<global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest, global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ConnectEmissary",
        __Marshaller_VRWorlds_Schemas_Browser_InterOp_ConnectEmissaryRequest,
        __Marshaller_VRWorlds_Schemas_Browser_InterOp_ConnectEmissaryReturn);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ConnectEmissary</summary>
    [grpc::BindServiceMethod(typeof(ConnectEmissary), "BindService")]
    public abstract partial class ConnectEmissaryBase
    {
      public virtual global::System.Threading.Tasks.Task<global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn> ConnectEmissary(global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ConnectEmissary</summary>
    public partial class ConnectEmissaryClient : grpc::ClientBase<ConnectEmissaryClient>
    {
      /// <summary>Creates a new client for ConnectEmissary</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ConnectEmissaryClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ConnectEmissary that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ConnectEmissaryClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ConnectEmissaryClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ConnectEmissaryClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn ConnectEmissary(global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectEmissary(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn ConnectEmissary(global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ConnectEmissary, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn> ConnectEmissaryAsync(global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectEmissaryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn> ConnectEmissaryAsync(global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ConnectEmissary, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ConnectEmissaryClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ConnectEmissaryClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ConnectEmissaryBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ConnectEmissary, serviceImpl.ConnectEmissary).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ConnectEmissaryBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ConnectEmissary, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryRequest, global::VRWorlds.Schemas.Browser.InterOp.ConnectEmissaryReturn>(serviceImpl.ConnectEmissary));
    }

  }
}
#endregion
